### ISSUE TITLE
Wyszukiwanie konkretnej strony

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/gov_backup#9]
Jeden z dwóch sposobów wyszukiwania to będzie szukanie konkretnej strony. 

Przykładowe User Story do zweryfikowania: chcę wyszukać stronę o sędziach trybunału konstytucyjnego. Wpisuję w okno wyszukiwania `trybunał konstytucyjny sędzia`. Najlepiej jakbym otrzymał `trybunal.gov.pl/o-trybunale/sedziowie-trybunalu/`

Jest kilka możliwości jak takie wyszukiwanie może działać:
1. Szukam wyłącznie w url
    - Plusy: jest to bardzo precyzyjne, dobre jak znam url
    - Minusy: mogę nie znaleźć wyszukiwanych informacji. Wpisując "konstytucyjny" odetnę sobie wyniki z trybunal.gov.pl, bo słowo konstytucyjny w url nie występuje
2. Szukanie w url i tytule (może także w opisie)
   - Plusy: łatwiej znaleźć stronę, która nas interesuje, nie muszę pamiętać dokładnego URL
   - Minusy: Nie jest to dokładne, idziemy trochę w stronę indeksowania większej ilości treści.

Skłaniam się ku temu, żeby zaimplementować opcję 2, bo będzie łatwiejsza dla użytkowników. Jak będą w przyszłości power userzy to można dla nich wprowadzić filtry, które pozwolą na większą kontrolę, np. na zapytania typu `formularz host:*.policja.gov.pl scheme:http`

**Comment by KrzysztofMadejski** [comment]
Decyzja: robimy jedną wyszukiwarkę, która zwróci też URLe/strony.

**Comment by KrzysztofMadejski** [comment]
@danielmacyszyn jak planujesz żeby wyszukiwanie było zrealizowane?

Teraz są dwie wyszukiwarki:
- jedna do wyszukiwania pelnotekstowego w treści strony
- druga do wyszukiwania stron (może szukać w url, tytule i opisie)

Widzę w komentarzu wyżej, że podjęliśmy decyzję o tym, żeby była jedna wyszukiwarka. Masz jakieś preferencje jak ona powinna zwracać wyniki, jak ważyć?

Wydaje mi się, że wyszukiwanie powinno brać pod uwagę:
- z dużym priorytetem url, tytuł
- z mniejszym: opis (meta: description) i treść strony

Powinna zwracać:
- highlighty we wszystkich powyższych polach

Proszę Cię o potwierdzenie / skomentowanie tego. Jak chcesz zwizualizować wyniki z takiej pojedynczej wyszukiwarki?

**Comment by danielmacyszyn** [comment]
Na początku mieliśmy dwa datasety z danymi govpackup: `www_portals` i `www_objects`. Zrozumiałem Twoją koncepcję dwóch wyszukiwarek tak, że jedna szuka tylko w `www_portals`, a druga tylko`www_objects`. Wydawało mi się, że to nadmiernie skomplikowanie pod względem UI i dlatego moja koncepcja jest taka, aby była jedna wyszukiwarka, która szuka w sumie tych datasetów, ale wyniki z `www_portals` mają wyższy priorytet.

Teraz jednak jest trochę inna koncepcja, ponieważ mamy *odrębne* datasety www_objects_versions. Wrócę do tego jak zapoznam się z mechanizmem indeksowania, który zaproponowałeś.
